version: '3.9'

volumes:
  postgres_data:
  static_data:
  media_data:

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
    image: nginx:1.19
    restart: always
    ports: 
      - "80:80"
    depends_on: 
      - web
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_data:/static
      - media_data:/media
  web:
    build: .
    expose:
      - "8000" 
    depends_on:
      - db
    volumes:
      - static_data:/orders/static
      - media_data:/orders/media
    env_file:
      - ./.env