# Generated by Django 3.2 on 2022-10-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0002_order_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='brand',
        ),
    ]
