# Generated by Django 3.2 on 2022-10-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0003_remove_order_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default=10.0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата'),
        ),
    ]
