# Generated by Django 3.2 on 2022-10-12 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0007_remove_order_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='model_brand', to='automobile.brand', verbose_name='Марка'),
            preserve_default=False,
        ),
    ]
