# Generated by Django 3.2 on 2022-10-13 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0012_remove_order_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='automobile.model', verbose_name='Модель, Марка'),
        ),
    ]
