# Generated by Django 3.2 on 2022-10-13 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0013_alter_order_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='automobile.brand', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='automobile.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='automobile.model', verbose_name='Модель, Марка'),
        ),
    ]
