# Generated by Django 3.2 on 2022-10-13 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0014_auto_20221013_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='automobile.model', verbose_name='Модель'),
        ),
    ]
