# Generated by Django 3.2 on 2022-10-13 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0015_alter_order_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='automobile.brand', verbose_name='Марка'),
        ),
    ]
