# Generated by Django 3.2 on 2022-10-13 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0016_alter_model_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='brand',
        ),
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='automobile.brand', verbose_name='Марка'),
            preserve_default=False,
        ),
    ]
