# Generated by Django 3.2 on 2022-10-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0018_brand_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='model',
        ),
        migrations.AddField(
            model_name='model',
            name='brand',
            field=models.ManyToManyField(related_name='brand', through='automobile.Order', to='automobile.Brand', verbose_name='Марка'),
        ),
    ]
