# Generated by Django 3.2 on 2022-10-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0019_auto_20221013_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='brand',
        ),
        migrations.AddField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(default=10.0, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='automobile.brand', verbose_name='Марка автомобиля'),
            preserve_default=False,
        ),
    ]
