# Generated by Django 3.2 on 2022-10-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0020_auto_20221013_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='brand',
        ),
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.ManyToManyField(related_name='orders', to='automobile.Brand', verbose_name='Марка'),
        ),
    ]
