# Generated by Django 3.2 on 2022-10-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0024_auto_20221013_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='title',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='order',
            name='model',
        ),
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(default=10.0, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='automobile.model', verbose_name='Автомобиль'),
            preserve_default=False,
        ),
    ]
