# Generated by Django 3.2 on 2022-10-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0025_auto_20221013_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='car',
            new_name='model',
        ),
    ]
