# Generated by Django 3.2 on 2022-10-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0026_rename_car_order_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='model',
            new_name='car',
        ),
    ]
