# Generated by Django 3.2 on 2022-10-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0027_rename_model_order_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(db_index=True, verbose_name='Дата'),
        ),
    ]
