# Generated by Django 3.2 on 2022-10-13 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0028_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
